'use client'

import { useMemo } from 'react'
import { useAuth } from '@/lib/auth-context'
import { useGarageStore } from '@/lib/store/garage-store'
import { AlertCircle, Bell, CheckCircle2, CircleAlert, Info } from 'lucide-react'
import { cn } from '@/lib/utils'

const icons = { info: Info, warning: CircleAlert, success: CheckCircle2, error: AlertCircle }
const colors = { info: 'text-blue-600 bg-blue-500/10', warning: 'text-amber-600 bg-amber-500/10', success: 'text-emerald-600 bg-emerald-500/10', error: 'text-red-600 bg-red-500/10' }
const relativeTime = (value: Date | string) => { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago` }

export function MyNotificationsPage() {
  const { user } = useAuth()
  const { notifications, companies, markNotificationAsRead, markAllNotificationsAsRead } = useGarageStore()
  const companyId = user?.roles.find((role) => role.scopeId)?.scopeId
  const relevant = useMemo(() => notifications.filter((notification) => notification.status !== 0 && (!notification.recipientType || notification.recipientType === 'all' || (notification.recipientType === 'company' && notification.recipientId === companyId) || (notification.recipientType === 'user' && notification.recipientId === user?.id))).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [notifications, companyId, user?.id])
  const isRead = (id: string, legacyRead?: boolean) => legacyRead || notifications.find((item) => item.id === id)?.reads?.some((read) => read.userId === user?.id && read.isRead)
  return <div className="mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Inbox</p><h1 className="mt-2 text-3xl font-bold tracking-tight">My Notifications</h1><p className="mt-2 text-sm text-muted-foreground">Updates and messages relevant to your account.</p></div><button type="button" className="text-sm font-semibold text-primary hover:underline" onClick={() => markAllNotificationsAsRead(user?.id)}>Mark all as read</button></div><div className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm">{relevant.length === 0 ? <div className="p-10 text-center"><Bell className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-semibold">You are all caught up</p></div> : <div className="divide-y divide-border">{relevant.map((notification) => { const type = notification.type === 'job' ? 'info' : notification.type === 'alert' ? 'warning' : notification.type === 'payment' ? 'success' : notification.type; const Icon = icons[type as keyof typeof icons] ?? Info; const read = isRead(notification.id, notification.read); return <button type="button" key={notification.id} onClick={() => markNotificationAsRead(notification.id, user?.id)} className={cn('flex w-full items-start gap-4 p-5 text-left transition-colors hover:bg-muted/30', !read && 'bg-primary/[0.03]')}><span className={cn('mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-full', colors[type as keyof typeof colors] ?? colors.info)}><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-3"><span className={cn('text-sm', !read ? 'font-bold text-foreground' : 'font-semibold text-foreground')}>{notification.title}</span><span className="shrink-0 text-xs text-muted-foreground">{relativeTime(notification.createdAt)}</span></span><span className="mt-1 block text-sm text-muted-foreground">{notification.message}</span></span>{!read && <span className="mt-2 size-2 shrink-0 rounded-full bg-primary" />}</button> })}</div>}</div></div>
}